out/plugin-array-detect.dylib:
	/opt/homebrew/bin/g++-15 "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "obj/array-detector-op0.o" "obj/array-detector.o" "obj/context-init-gcc.o" "obj/context-init.o" "obj/context.o" "obj/gcc-ext-util.o" "obj/info-print.o" "obj/plugin-top.o" "obj/state.o" -o "out/plugin-array-detect.dylib"

obj/array-detector-op0.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/array-detector-op0.cc" -o "obj/array-detector-op0.o"

obj/array-detector.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/array-detector.cc" -o "obj/array-detector.o"

obj/context-init-gcc.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/context-init-gcc.cc" -o "obj/context-init-gcc.o"

obj/context-init.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/context-init.cc" -o "obj/context-init.o"

obj/context.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/context.cc" -o "obj/context.o"

obj/gcc-ext-util.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/gcc-ext-util.cc" -o "obj/gcc-ext-util.o"

obj/info-print.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/info-print.cc" -o "obj/info-print.o"

obj/plugin-top.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/plugin-top.cc" -o "obj/plugin-top.o"

obj/state.o:
	/opt/homebrew/bin/g++-15 -c "-fPIC" "-fno-rtti" "-shared" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin" "-I" "/opt/homebrew/Cellar/gcc/15.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin25/15/plugin/include" "-I" "include" "-I" "config" "-undefined" "dynamic_lookup" "-O2" "-Wall" "-Wextra" "-std=c++17" "-L/opt/homebrew/Cellar/gmp/6.3.0/lib" "-lgmp" "-I/opt/homebrew/Cellar/gmp/6.3.0/include" "-I" "/opt/homebrew/opt/libmpc/include" "-L" "/opt/homebrew/opt/libmpc/lib" "-I" "/opt/homebrew/opt/mpfr/include" "-L" "/opt/homebrew/opt/mpfr/lib" "src/state.cc" -o "obj/state.o"

obj/array-detector-op0.o: include/gcc-ext-util.hh include/context-init.hh include/array-detector-op0.hh include/state.hh include/prelude.hh src/array-detector-op0.cc
obj/array-detector.o: include/array-detector.hh include/state.hh include/prelude.hh src/array-detector.cc
obj/context-init-gcc.o: include/context.hh include/context-init.hh include/gcc-common.hh src/context-init-gcc.cc
obj/context-init.o: include/context.hh include/context-init.hh include/state.hh include/prelude.hh src/context-init.cc
obj/context.o: include/context.hh src/context.cc
obj/gcc-ext-util.o: include/gcc-ext-util.hh include/info.hh src/gcc-ext-util.cc
obj/info-print.o: include/info-print.hh src/info-print.cc
obj/plugin-top.o: include/context.hh include/context-init.hh include/array-detector.hh include/gcc-common.hh include/array-detector-op0.hh include/state.hh include/prelude.hh src/plugin-top.cc
obj/state.o: include/state.hh src/state.cc
out/plugin-array-detect.dylib: obj/array-detector-op0.o obj/array-detector.o obj/context-init-gcc.o obj/context-init.o obj/context.o obj/gcc-ext-util.o obj/info-print.o obj/plugin-top.o obj/state.o

clean:
	rm -rv obj/*
	rm -rv out/*

test: out/plugin-array-detect.dylib
	cd ../test/test-xercese; racket build-xercese.rkt

